### PR TITLE
Tried to move data to seperate file

### PR DESCRIPTION
**Pull request by nikiljos**
I have created an object in pages/data.js and moved data to it....

I was just trying out what I said in https://github.com/akash-santhosh/tools/issues/11

I'm not sure if it is the right way to implement it... I'm using Next.JS for the first time😀

Works fine in my local machine

image

### CODE REVIEW

**Comment by nikiljos** [comment]
image
When i ran npm install my package-lock.json changed a lot... I haven't committed it, Is that why vercel deployment failed? Should i commit it?

**Comment by nikiljos** [comment]
image
Sorry i messed it up 😅

**Comment by akash-santhosh** [comment]
yap. something wrong with vercel's os config

**Comment by nikiljos** [comment]
deployment got fine after my 2nd commit right?

**Comment by akash-santhosh** [comment]
conflict

**Comment by nikiljos** [comment]
I would resolve the conflict now... Is the method right?

**Comment by nikiljos** [comment]
> conflict

happened bcoz you merged https://github.com/akash-santhosh/tools/pull/13 before this https://github.com/akash-santhosh/tools/pull/12

**Pull request merged**
